CREATE DATABASE QUANLYBANHANG

USE QUANLYBANHANG

CREATE TABLE KHACHHANG
(
	MAKH char(4) NOT NULL,
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	NGDK smalldatetime,
	DOANHSO money,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)

